views:
  - output: "index.html"
    template: "index.html"
  - output: "en/index.html"
    template: "en/index.html"
  - output: "zh/index.html"
    template: "zh/index.html"
  - output: "en/organizations.html"
    query: "en_organizations.rq"
    template: "org_index.html"
  - output: "en/collections.html"
    query: "en_collections.rq"
    template: "collections_index.html"
  - output: "en/{{qid}}.html"
    query: "en_collections.rq"
    template: "collection.html"
  - output: "en/{{qid}}.html"
    query: "en_organizations.rq"
    template: "organization.html"
  - output: "zh/organizations.html"
    query: "zh_organizations.rq"
    template: "org_index.html"
  - output: "zh/{{qid}}.html"
    query: "zh_collections.rq"
    template: "collection.html"
  - output: "zh/{{qid}}.html"
    query: "zh_organizations.rq"
    template: "organization.html"
  - output: "zh/collections.html"
    query: "zh_collections.rq"
    template: "collections_index.html"
  - output: "en/people.html"
    query: "en_people.rq"
    template: "people_index.html"
  - output: "zh/people.html"
    query: "zh_people.rq"
    template: "people_index.html"
  - output: "en/{{qid}}.html"
    query: "en_people.rq"
    template: "person.html"
  - output: "zh/{{qid}}.html"
    query: "zh_people.rq"
    template: "person.html"
  - output: "en/subjects.html"
    query: "en_subjects.rq"
    template: "en/subjects_index.html"
  - output: "zh/subjects.html"
    query: "zh_subjects.rq"
    template: "zh/subjects_index.html"
  - output: "en/materials.html"
    query: "en_materials.rq"
    template: "en/materials_index.html"
  - output: "zh/materials.html"
    query: "zh_materials.rq"
    template: "zh/materials_index.html"
  - output: "en/about.html"
    template: "en/about.html"
  - output: "zh/about.html"
    template: "zh/about.html"
  - output: "en/data_model.html"
    template: "en/data_model.html"
  - output: "en/maintainers.html"
    query: "en_maintainers.rq"
    template: "en/maintainers_index.html"
  - output: "zh/maintainers.html"
    query: "zh_maintainers.rq"
    template: "zh/maintainers_index.html"