views:
  - output: "index.html"
    template: "en/index.html"
  - output: "en/index.html"
    template: "en/index.html"
  - output: "zh/index.html"
    template: "zh/index.html"
  - output: "en/organizations.html"
    query: "en/organizations.rq"
    template: "generic/org_index.html"
  - output: "en/collections.html"
    query: "en/collections.rq"
    template: "generic/collections_index.html"
  - output: "en/{{qid}}.html"
    query: "en/collections.rq"
    template: "generic/collection.html"
  - output: "en/{{qid}}.html"
    query: "en/organizations.rq"
    template: "generic/organization.html"
  - output: "zh/organizations.html"
    query: "zh/organizations.rq"
    template: "generic/org_index.html"
  - output: "zh/{{qid}}.html"
    query: "zh/collections.rq"
    template: "generic/collection.html"
  - output: "zh/{{qid}}.html"
    query: "zh/organizations.rq"
    template: "generic/organization.html"
  - output: "zh/collections.html"
    query: "zh/collections.rq"
    template: "generic/collections_index.html"
  - output: "en/people.html"
    query: "en/people.rq"
    template: "generic/people_index.html"
  - output: "zh/people.html"
    query: "zh/people.rq"
    template: "generic/people_index.html"
  - output: "en/{{qid}}.html"
    query: "en/people.rq"
    template: "generic/person.html"
  - output: "zh/{{qid}}.html"
    query: "zh/people.rq"
    template: "generic/person.html"
  - output: "en/subjects.html"
    query: "en/subjects.rq"
    template: "en/subjects_index.html"
  - output: "zh/subjects.html"
    query: "zh/subjects.rq"
    template: "zh/subjects_index.html"
  - output: "en/materials.html"
    query: "en/materials.rq"
    template: "en/materials_index.html"
  - output: "zh/materials.html"
    query: "zh/materials.rq"
    template: "zh/materials_index.html"
  - output: "en/about.html"
    template: "en/about.html"
  - output: "zh/about.html"
    template: "zh/about.html"
  - output: "en/data_model.html"
    template: "en/data_model.html"
  - output: "zh/data_model.html"
    template: "zh/data_model.html"
  - output: "en/maintainers.html"
    query: "en/maintainers.rq"
    template: "en/maintainers_index.html"
  - output: "zh/maintainers.html"
    query: "zh/maintainers.rq"
    template: "zh/maintainers_index.html"
  - output: "en/credits.html"
    template: "en/credits.html"
  - output: "zh/credits.html"
    template: "zh/credits.html"