SELECT ?qid ?materialLabel (COUNT(?collection) AS ?count)
WHERE {
   # variables used in query
   BIND(wdt:P7 AS ?instanceOf).
   BIND(wdt:P38 AS ?hasMaterial).
   BIND(wd:Q85 AS ?ChinatownCollection).
   BIND("http://ec2-34-227-69-60.compute-1.amazonaws.com/entity/" AS ?baseURI).

   ?collection ?instanceOf ?ChinatownCollection;
               ?hasMaterial ?material.
   BIND(REPLACE(STR(?material), ?baseURI, "") AS ?qid).
   SERVICE wikibase:label { bd:serviceParam wikibase:language "zh". }
} GROUP BY ?qid ?materialLabel ORDER BY DESC(?count)