SELECT ?qid ?maintainerLabel (COUNT(?collection) AS ?count)
WHERE {
   ?collection wdt:P7 wd:Q85;
               wdt:P11 ?maintainer.
   BIND(REPLACE(STR(?maintainer), "http://ec2-34-227-69-60.compute-1.amazonaws.com/entity/", "") AS ?qid).
   SERVICE wikibase:label { bd:serviceParam wikibase:language "zh,en". }
} GROUP BY ?qid ?maintainerLabel ORDER BY DESC(?count)