SELECT ?title ?qid ?personLabel ?createdCollections ?foundedOrganizations ?maintainsCollections
WHERE {
   ?person wdt:P7 wd:Q21.
   BIND("[People in Chinese]" as ?title).
   BIND(REPLACE(STR(?person), "http://ec2-34-227-69-60.compute-1.amazonaws.com/entity/", "") AS ?qid).
   SERVICE wikibase:label { bd:serviceParam wikibase:language "zh,en". }
   {
     SELECT ?innerPerson
            (group_concat(distinct ?createdCollectionLabel; separator="; ") as ?createdCollections)
            (group_concat(distinct ?foundedOrganizationLabel; separator="; ") as ?foundedOrganizations)
            (group_concat(distinct ?maintainsCollectionLabel; separator="; ") as ?maintainsCollections)
     WHERE {
       ?innerPerson wdt:P7 wd:Q21.
       OPTIONAL{?innerPerson ^wdt:P28 ?createdCollection}
       OPTIONAL{?innerPerson ^wdt:P10 ?foundedOrganization}
       OPTIONAL{?innerPerson ^wdt:P11 ?maintainsCollection}
       SERVICE wikibase:label {bd:serviceParam wikibase:language "zh,en".
                               ?createdCollection rdfs:label ?createdCollectionLabel.
                               ?foundedOrganization rdfs:label ?foundedOrganizationLabel.
                               ?maintainsCollection rdfs:label ?maintainsCollectionLabel.
       }
     } GROUP BY ?innerPerson 
   }
  filter(?innerPerson = ?person)
} ORDER BY (?personLabel)