SELECT DISTINCT ?qid ?collectionLabel WHERE {
  # variables used in query
  BIND(wdt:P7 AS ?instanceOf).
  BIND(wdt:P11 AS ?hasMaintainer).
  BIND(wd:Q85 AS ?ChinatownCollection).
  BIND("http://ec2-34-227-69-60.compute-1.amazonaws.com/entity/" AS ?baseURI).

  ?collection ?instanceOf ?ChinatownCollection;
               ?hasMaintainer wd:{{.}}.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
  BIND(REPLACE(STR(?collection), ?baseURI, "") AS ?qid)
} ORDER BY ?collectionLabel